#!/usr/bin/env bash

build/src/Main/fgfs \
	--dis=socket,in,10,255.255.255.255,3000,broadcast \
	--site=22317 \
	--application=44635 \
	--ownship_id=1111 \
	--lat=31.13896312 \
	--lon=-97.71213774258472 \
	--heading=270 \
	--timeofday=morning \
	--aircraft=uh60 \
	--callsign=Test2 \
	--config=./models.xml \
	--data=./ap \
	${*}

	# --multiplay=out,10,127.0.0.1,5001 \
	# --multiplay=in,10,127.0.0.1,5000 \
